### ISSUE TITLE
Flux RSS cassé

### ISSUE THREAD

**Issue by SiegfriedEhret** [abenoit/personal-blog#3]
Bonjour,

D'après le pied de page il doit y avoir un flux RSS à https://amelie.tech/feed.xml, mais c'est une 404.
Ce serait top si tu peux corriger ça, car les flux RSS c'est le bien :)

Merci d'avance !

**Comment by abenoit** [comment]
Hello Siegfried,

Merci à toi pour le report et pour ton intérêt pour le site ❤️
C'est maintenant réparé !
